[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"

[[deploy.env]]
key = "PYTHON_VERSION"
value = "3.11"

[[deploy.env]]
key = "NIXPACKS_PYTHON_VERSION"
value = "3.11" 