[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/docs"
healthcheckTimeout = 100

[deploy.env]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11" 