[build]
builder = "buildpacks"
buildCommand = "./build.sh"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/docs"
healthcheckTimeout = 100

[deploy.env]
PYTHON_VERSION = "3.11.7"
PYTHONPATH = "." 